// SPDX-FileCopyrightText: 2023 James Graham <james.h.graham@protonmail.com>
// SPDX-License-Identifier: LGPL-2.1-or-later

#pragma once

#include "avatar.h"
#include "util.h"

#include <QtCore/QObject>

namespace Quotient {
class User;
class Room;

class QUOTIENT_API UserInContext : public QObject {
    Q_OBJECT
    Q_PROPERTY(QString id READ id CONSTANT STORED false)
    Q_PROPERTY(bool isGuest READ isGuest CONSTANT STORED false)
    Q_PROPERTY(int hue READ hue CONSTANT STORED false)
    Q_PROPERTY(qreal hueF READ hueF CONSTANT STORED false)
    Q_PROPERTY(QColor color READ color CONSTANT)
    Q_PROPERTY(QString name READ name NOTIFY defaultNameChanged STORED false)
    Q_PROPERTY(QString displayName READ displayname NOTIFY defaultNameChanged STORED false)
    Q_PROPERTY(QString fullName READ fullName NOTIFY defaultNameChanged STORED false)
    Q_PROPERTY(QString avatarMediaId READ avatarMediaId NOTIFY defaultAvatarChanged STORED false)
    Q_PROPERTY(QUrl avatarUrl READ avatarUrl NOTIFY defaultAvatarChanged STORED false)

public:
    UserInContext(const User* user, const Room* room);

    /** Get unique stable user id
     * User id is generated by the server and is not changed ever.
     */
    QString id() const;

    /** Get the name chosen by the user
     * This may be empty if the user didn't choose the name or cleared
     * it. If the user is bridged, the bridge postfix (such as '(IRC)')
     * is stripped out. No disambiguation for the room is done.
     * \sa displayName
     */
    QString name() const;

    /** Get the displayed user name
     * When \p room is null, this method returns result of name() if
     * the name is non-empty; otherwise it returns user id.
     * When \p room is non-null, this call is equivalent to
     * Room::roomMembername invocation for the user (i.e. the user's
     * disambiguated room-specific name is returned).
     * \sa name, id, fullName, Room::roomMembername
     */
    QString displayname() const;

    /** Get user name and id in one string
     * The constructed string follows the format 'name (id)'
     * which the spec recommends for users disambiguation in
     * a room context and in other places.
     * \sa displayName, Room::roomMembername
     */
    QString fullName() const;

    /** Whether the user is a guest
     * As of now, the function relies on the convention used in Synapse
     * that guests and only guests have all-numeric IDs. This may or
     * may not work with non-Synapse servers.
     */
    bool isGuest() const;

    /** Hue color component of this user based on id.
     * The implementation is based on XEP-0392:
     * https://xmpp.org/extensions/xep-0392.html
     * Naming and ranges are the same as QColor's hue methods:
     * https://doc.qt.io/qt-5/qcolor.html#integer-vs-floating-point-precision
     */
    int hue() const;
    qreal hueF() const;

    QColor color() const;

    /// Get a reference to a user avatar object for a given room
    /*! This reference should be considered short-lived: processing the next
     * room member event for this user may (or may not) invalidate it.
     */
    const Avatar& avatarObject() const;
    Q_INVOKABLE QImage avatar(int dimension) const;
    Q_INVOKABLE QImage avatar(int requestedWidth, int requestedHeight) const;
    QImage avatar(int width, int height, const Avatar::get_callback_t& callback) const;

    QString avatarMediaId() const;
    QUrl avatarUrl() const;

public Q_SLOTS:
    /// Check whether the user is in ignore list
    bool isIgnored() const;

Q_SIGNALS:
    void defaultNameChanged();
    void defaultAvatarChanged();

private:
    class Private;
    ImplPtr<Private> d;
};
} // namespace Quotient
